name: flutter_application_1
description: "Well360 - AI Health Analyzer application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.0
  geolocator: ^11.0.0
  cupertino_icons: ^1.0.8
  file_picker: ^8.0.0
  video_player: ^2.8.0
  image_picker: ^1.0.7
  camera: ^0.10.5+9
  fl_chart: ^0.66.0
  shared_preferences: ^2.5.4
  intl: ^0.20.2
  image: ^4.7.2
  google_fonts: ^8.0.0
  flutter_local_notifications: ^20.0.0
  timezone: ^0.10.1
  google_mlkit_face_detection: ^0.13.2
  google_sign_in: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
